version: '3.8'

services:
  flight-bot:
    build: .
    container_name: flight-schedule-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_DOM_URL=${API_DOM_URL}
      - API_INTER_URL=${API_INTER_URL}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./logs:/app/logs
    networks:
      - flight-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  flight-network:
    driver: bridge